from typing import Optional, List, Tuple, Union
from uuid import UUID

from ..core.supabase_client import get_admin_client
from ..core.async_runner import execute_query
from ..schemas.user import User, UserCreate, UserUpdate, UserWithPassword


class UserModel:
    """Model for user operations with Supabase (Non-blocking async execution)."""

    TABLE_NAME = "Users"

    @staticmethod
    async def create(user_data) -> User:
        """Create a new user."""

        supabase = get_admin_client()

        # Convert Pydantic model to dictionary
        if hasattr(user_data, "model_dump"):
            data = user_data.model_dump(exclude_unset=True)
        else:
            data = dict(user_data)

        # Remove fields that should be generated by the database
        if data.get("id") in ("", None):
            data.pop("id", None)

        # UUID columns must never receive an empty string.
        uuid_fields = [
            "organization_id",
            "clinic_id",
        ]

        for field in uuid_fields:
            if field in data and data[field] == "":
                data[field] = None

        # Convert UUID objects to strings for Supabase
        for field in uuid_fields:
            if isinstance(data.get(field), UUID):
                data[field] = str(data[field])

        query = (
            supabase
            .table(UserModel.TABLE_NAME)
            .insert(data)
        )
        response = await execute_query(query)

        if not response.data:
            raise Exception("Failed to create user.")

        return User(**response.data[0])

    @staticmethod
    async def get_by_id(user_id: str) -> Optional[User]:
        """Get a user by ID."""

        supabase = get_admin_client()

        query = (
            supabase
            .table(UserModel.TABLE_NAME)
            .select("*")
            .eq("id", user_id)
        )
        response = await execute_query(query)

        if response.data:
            return User(**response.data[0])

        return None

    @staticmethod
    async def get_by_email(email: str) -> Optional[User]:
        """Get a user by email (password excluded — safe for API responses)."""

        supabase = get_admin_client()

        query = (
            supabase
            .table(UserModel.TABLE_NAME)
            .select("*")
            .eq("email", email)
            .limit(1)
        )
        response = await execute_query(query)

        if response.data:
            return User(**response.data[0])

        return None

    @staticmethod
    async def get_by_email_with_password(email: str) -> Optional[UserWithPassword]:
        """Get a user by email INCLUDING the hashed password.
        INTERNAL USE ONLY — for login/authentication verification.
        Never return this object directly from an API endpoint.
        """

        supabase = get_admin_client()

        query = (
            supabase
            .table(UserModel.TABLE_NAME)
            .select("*")
            .eq("email", email)
            .limit(1)
        )
        response = await execute_query(query)

        if response.data:
            return UserWithPassword(**response.data[0])

        return None

    @staticmethod
    async def get_all(
        limit: int = 100,
        offset: int = 0,
        include_deactivated: bool = False,
        return_count: bool = False
    ) -> Union[List[User], Tuple[List[User], int]]:
        """Get all users across all organizations with pagination and soft delete filtering."""

        supabase = get_admin_client()

        query = supabase.table(UserModel.TABLE_NAME).select("*", count="exact")
        if not include_deactivated:
            query = query.eq("is_active", True)

        query = query.range(offset, offset + limit - 1)
        response = await execute_query(query)

        users = [User(**user) for user in response.data]
        if return_count:
            total = response.count if response.count is not None else len(users)
            return users, total
        return users

    @staticmethod
    async def update(
        user_id: str,
        user_data: UserUpdate
    ) -> Optional[User]:
        """Update a user."""

        supabase = get_admin_client()

        data = user_data.model_dump(
            exclude_unset=True,
            exclude_none=True
        )

        uuid_fields = [
            "organization_id",
            "clinic_id",
        ]

        for field in uuid_fields:
            if data.get(field) == "":
                data[field] = None

            if isinstance(data.get(field), UUID):
                data[field] = str(data[field])

        query = (
            supabase
            .table(UserModel.TABLE_NAME)
            .update(data)
            .eq("id", user_id)
        )
        response = await execute_query(query)

        if response.data:
            return User(**response.data[0])

        return None

    @staticmethod
    async def delete(user_id: str) -> bool:
        """Soft delete a user."""

        supabase = get_admin_client()

        query = (
            supabase
            .table(UserModel.TABLE_NAME)
            .update({"is_active": False})
            .eq("id", user_id)
        )
        response = await execute_query(query)

        return len(response.data) > 0

    @staticmethod
    async def get_by_organization(
        org_id: str,
        limit: int = 100,
        offset: int = 0,
        include_deactivated: bool = False,
        return_count: bool = False
    ) -> Union[List[User], Tuple[List[User], int]]:
        """Get all users in an organization with default soft delete filtering."""

        supabase = get_admin_client()

        query = (
            supabase
            .table(UserModel.TABLE_NAME)
            .select("*", count="exact")
            .eq("organization_id", org_id)
        )
        if not include_deactivated:
            query = query.eq("is_active", True)

        query = query.range(offset, offset + limit - 1)
        response = await execute_query(query)

        users = [User(**user) for user in response.data]
        if return_count:
            total = response.count if response.count is not None else len(users)
            return users, total
        return users

    @staticmethod
    async def get_by_clinic(
        clinic_id: str,
        include_deactivated: bool = False,
        limit: int = 100,
        offset: int = 0,
        return_count: bool = False
    ) -> Union[List[User], Tuple[List[User], int]]:
        """Get all users assigned to a clinic with soft delete filtering."""

        supabase = get_admin_client()

        query = (
            supabase
            .table(UserModel.TABLE_NAME)
            .select("*", count="exact")
            .contains(
                "assigned_clinics",
                [clinic_id]
            )
        )
        if not include_deactivated:
            query = query.eq("is_active", True)

        query = query.range(offset, offset + limit - 1)
        response = await execute_query(query)

        users = [User(**user) for user in response.data]
        if return_count:
            total = response.count if response.count is not None else len(users)
            return users, total
        return users

    @staticmethod
    async def count_by_organization(
        org_id: str
    ) -> int:
        """Count users in an organization."""

        supabase = get_admin_client()

        query = (
            supabase
            .table(UserModel.TABLE_NAME)
            .select("id", count="exact")
            .eq("organization_id", org_id)
        )
        response = await execute_query(query)

        return response.count or 0