import pytest
from unittest.mock import AsyncMock, patch
from openai import RateLimitError
from app.core.config import settings
from app.services.openai_service import OpenAIService

@pytest.mark.asyncio
async def test_ai_fallback_on_primary_failure():
    """Verify that OpenAIService attempts fallback model if primary model fails."""
    
    # Mock client completions create: fail on primary, succeed on fallback
    with patch("app.services.openai_service.client.chat.completions.create", new_callable=AsyncMock) as mock_create:
        async def mock_completion(model, messages, **kwargs):
            if model == settings.AI_PRIMARY_MODEL:
                raise RateLimitError(f"Rate limit reached on {settings.AI_PRIMARY_MODEL}", response=AsyncMock(status_code=429), body={})
            # Fallback model succeeds
            mock_choice = AsyncMock()
            mock_choice.message.content = "Summary successfully generated by fallback model."
            mock_resp = AsyncMock()
            mock_resp.choices = [mock_choice]
            return mock_resp

        mock_create.side_effect = mock_completion

        summary = await OpenAIService.generate_lead_summary("Patient is looking for teeth whitening consultation.")
        assert "fallback model" in summary
